package pipeline

import (
	"context"
	"fmt"
	"os"
	"path/filepath"
	"sync"

	"azure-resource-downloader/internal/logger"
	"azure-resource-downloader/internal/models"

	"gopkg.in/yaml.v3"
)

// Writer handles writing resources to disk
type Writer struct {
	outputDir   string
	workerCount int
	dryRun      bool
}

// NewWriter creates a new writer
func NewWriter(outputDir string, workerCount int, dryRun bool) *Writer {
	return &Writer{
		outputDir:   outputDir,
		workerCount: workerCount,
		dryRun:      dryRun,
	}
}

// Write processes transform results and writes them to disk
func (w *Writer) Write(ctx context.Context, transformResults <-chan *models.TransformResult) <-chan *models.WriteResult {
	out := make(chan *models.WriteResult)

	go func() {
		defer close(out)

		// Start worker pool
		var wg sync.WaitGroup
		for i := 0; i < w.workerCount; i++ {
			wg.Add(1)
			go w.writeWorker(ctx, transformResults, out, &wg)
		}

		// Wait for all workers to complete
		wg.Wait()
	}()

	return out
}

// writeWorker processes write operations
func (w *Writer) writeWorker(ctx context.Context, transformResults <-chan *models.TransformResult, writeResults chan<- *models.WriteResult, wg *sync.WaitGroup) {
	defer wg.Done()

	for transformResult := range transformResults {
		select {
		case <-ctx.Done():
			writeResults <- &models.WriteResult{
				ResourceID: transformResult.ResourceID,
				Error:      ctx.Err(),
			}
			return
		default:
			// Check if transform had an error
			if transformResult.Error != nil {
				writeResults <- &models.WriteResult{
					ResourceID: transformResult.ResourceID,
					Error:      transformResult.Error,
				}
				continue
			}

			result := w.writeResource(transformResult)
			writeResults <- result
		}
	}
}

// writeResource writes a single resource to disk
func (w *Writer) writeResource(transformResult *models.TransformResult) *models.WriteResult {
	log := logger.Default

	log.Debug("Writing resource files",
		"resource_id", transformResult.ResourceID,
		"name", transformResult.DisplayName,
		"type", transformResult.ResourceType)

	// Create resource type directory
	resourceTypeDir := filepath.Join(w.outputDir, transformResult.ResourceType)

	if !w.dryRun {
		if err := os.MkdirAll(resourceTypeDir, 0755); err != nil {
			log.Error("Failed to create directory",
				"resource_id", transformResult.ResourceID,
				"directory", resourceTypeDir,
				"error", err)
			return &models.WriteResult{
				ResourceID: transformResult.ResourceID,
				Error:      fmt.Errorf("failed to create directory: %w", err),
			}
		}
	}

	// Write YAML file
	yamlPath := filepath.Join(resourceTypeDir, transformResult.SanitizedName+".yaml")
	if !w.dryRun {
		yamlData, err := yaml.Marshal(transformResult.CleanedData)
		if err != nil {
			log.Error("Failed to marshal YAML",
				"resource_id", transformResult.ResourceID,
				"error", err)
			return &models.WriteResult{
				ResourceID: transformResult.ResourceID,
				Error:      fmt.Errorf("failed to marshal YAML: %w", err),
			}
		}

		if err := os.WriteFile(yamlPath, yamlData, 0644); err != nil {
			log.Error("Failed to write YAML file",
				"resource_id", transformResult.ResourceID,
				"path", yamlPath,
				"error", err)
			return &models.WriteResult{
				ResourceID: transformResult.ResourceID,
				Error:      fmt.Errorf("failed to write YAML file: %w", err),
			}
		}
	}

	// Write Terraform import file
	terraformPath := filepath.Join(resourceTypeDir, transformResult.SanitizedName+".tf")
	if !w.dryRun {
		terraformContent := fmt.Sprintf("# Terraform import statement for %s\n# Generated by azure-resource-downloader\n\n%s\n",
			transformResult.DisplayName,
			transformResult.TerraformImport,
		)

		if err := os.WriteFile(terraformPath, []byte(terraformContent), 0644); err != nil {
			log.Error("Failed to write Terraform file",
				"resource_id", transformResult.ResourceID,
				"path", terraformPath,
				"error", err)
			return &models.WriteResult{
				ResourceID: transformResult.ResourceID,
				Error:      fmt.Errorf("failed to write Terraform file: %w", err),
			}
		}
	}

	log.Debug("Resource files written successfully",
		"resource_id", transformResult.ResourceID,
		"yaml_path", yamlPath,
		"terraform_path", terraformPath)

	return &models.WriteResult{
		ResourceID:    transformResult.ResourceID,
		YAMLPath:      yamlPath,
		TerraformPath: terraformPath,
		Error:         nil,
	}
}
